{% set version = "0.16.1" %}

package:
  name: pyagrum
  version: {{ version }}

source:
  fn: pyagrum-{{ version }}.tar.bz2
  url: https://gitlab.com/agrumery/aGrUM/-/archive/{{ version }}/aGrUM-{{ version }}.tar.bz2
  sha256: a1204b5d995d5404e1cc67911ed907aab90f2971bd50f495711f39196dc1a014
build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
  host:
    - python
    - numpy
    - pydotplus
    - six
    - configparser  # [py2k]
  run:
    - python
    - numpy
    - pydotplus
    - six
    - configparser  # [py2k]
    - matplotlib

test:
  requires:
    - ipykernel
  imports:
    - pyAgrum
    - pyAgrum.lib.bn2roc
    - pyAgrum.lib.bn2scores
    - pyAgrum.lib.bn_vs_bn
    - pyAgrum.lib.dynamicBN
    - pyAgrum.lib.notebook
    - pyAgrum.lib.pretty_print

about:
  home: http://agrum.gitlab.io/
  license: LGPL3
  license_file: COPYRIGHT.txt
  summary: A wrapper for the Agrum library, to make flexible and scalable probabilistic graphical models.

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
    - aspard
