{% set version = "0.9.3" %}

package:
  name: pyagrum
  version: {{ version }}

source:
  git_url: git://forge.lip6.fr/aGrUM
  git_tag: {{ version }}
  patches:
    - fix-python-detection.patch
    - dont-rebuild-lib.patch
    - gcc48.patch

build:
  number: 0
  # only linux is supported
  skip: true  # [osx or win]

requirements:
  build:
    - toolchain
    - python
    - numpy
    - cmake
    - swig

  run:
    - python
    - numpy

test:
  imports:
    - pyAgrum

about:
  home: https://forge.lip6.fr/projects/aGrUM/wiki
  license: GPLv3
  license_file: COPYRIGHT.txt
  summary: C++ Bayesian networks library

extra:
  recipe-maintainers:
    - jschueller
