{% set version = "0.19.1" %} 

package:
  name: pyagrum
  version: {{ version }}

source:
  fn: pyagrum-{{ version }}.tar.bz2
  url: https://gitlab.com/agrumery/aGrUM/-/archive/{{ version }}/aGrUM-{{ version }}.tar.bz2
  sha256: f7ec617a98811d019fd8f2ce08e6b196953b6bac6d3251ee331f9f8c49188f24

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pyagrum', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - curl  # [win]
    - 7za  # [win]
  host:
    - python
    - numpy
    - pydotplus
    - six
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas
  run:
    - python
    - numpy
    - pydotplus
    - six
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas

test:
  requires:
    - ipykernel
  imports:
    - pyAgrum
    - pyAgrum.lib.bn2roc
    - pyAgrum.lib.bn2scores
    - pyAgrum.lib.bn_vs_bn
    - pyAgrum.lib.dynamicBN
    # - pyAgrum.lib.notebook
    - pyAgrum.lib.pretty_print

about:
  home: http://agrum.gitlab.io/
  license: LGPL-3.0-only
  license_file: COPYRIGHT.txt
  summary: pyAgrum is a Python wrapper for the C++ aGrUM library. It provides a high-level interface to the part of aGrUM allowing to create, model, learn, use, calculate with and embed Bayesian networks and other graphical models. Some specific (Python and C++) codes are added in order to simplify and extend the aGrUM API.

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
    - aspard
