{% set version = "0.9.3" %}

package:
  name: pyagrum
  version: {{ version }}

source:
  git_url: git://forge.lip6.fr/aGrUM
  git_tag: {{ version }}
  patches:
    - fix-python-detection.patch
    - dont-rebuild-lib.patch
    - gcc48.patch
    - define-PYTHON_INSTALL.patch
    - fix-pyagrum-install.patch

build:
  number: 0
  features:
    - vc14  # [win and py35]
  skip: true  # [win and (py27 or py34)]

requirements:
  build:
    # use gcc instead of clang on osx because of the cxx14 requirement
    - toolchain  # [linux]
    - gcc  # [osx]
    - python
    - numpy
    - cmake

  run:
    - python
    - numpy
    - libgcc  # [osx]

test:
  imports:
    - pyAgrum

about:
  home: https://forge.lip6.fr/projects/aGrUM/wiki
  license: GPLv3
  license_file: COPYRIGHT.txt
  summary: C++ Bayesian networks library

extra:
  recipe-maintainers:
    - jschueller
