{% set version = "0.14.3" %}

package:
  name: pyagrum
  version: {{ version }}

source:
  fn: pyagrum-{{ version }}.tar.bz2
  url: https://gitlab.com/agrumery/aGrUM/-/archive/{{ version }}/aGrUM-{{ version }}.tar.bz2
  sha256: f36a30263bf9c6a13b9519bf332b85f47c1d53e8278a410629528c29b7d3045a

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
  host:
    - python
    - numpy
  run:
    - python
    - numpy
    - pydotplus
    - matplotlib

test:
  requires:
    - ipykernel
  imports:
    - pyAgrum
    - pyAgrum.lib.bn2roc
    - pyAgrum.lib.bn2scores
    - pyAgrum.lib.bn_vs_bn
    - pyAgrum.lib.dynamicBN
    - pyAgrum.lib.notebook
    - pyAgrum.lib.pretty_print

about:
  home: http://agrum.gitlab.io/
  license: GPL3
  license_file: COPYRIGHT.txt
  summary: A wrapper for the Agrum library, to make flexible and scalable probabilistic graphical models.

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
    - aspard
