travis:
  secure:
    BINSTAR_TOKEN: ElsEujlOTUfy++GZy6vVSCf5hcVjSVrHiZIFy4TXywvV1lv/BeH+oEZOjFN7008FU3T/kBotL6tr0OLE3/UomGcyM9Jv2ATMEkXzyJT/QcaHkZwQPf13Ub8QHzlgOY/LhC3GGlT97TBoeTxAY2SiG8JATRTQVtF4hIwrkiJItMl+cDuJZ4pXd4Ds2M0X2biz5b75OQ12NtjzA2JdICyBQOoa6vBXLJhcUbJicaBazbkm/SGT/bTU487k/3MO1NW431jAdrQfo8pURUZWovbF0CJWP5qIIlpxZ87OC+qTvbRgyeHo1fZnWXI4vqOOh26KRoWxclArhtP0lCcE0rel48Vq+zXb6/GPZPCy5E779gFAXk8gvXQ86QQZmLXA3UMq7MUX9vOmRKFiIAN59/IRDNU607je69bcucCizlR1rwS0xap5wbWsklLzZCaN2VFF7pGE876peV9J/Bh3yS4n+r//ZibMiHqcVrkgIR5sgbuxQUKFEnrqHZOnB8993VEGVcCPyq6XA5m6NjnkEBAYZAVjDMvLZ8QMAIotb3TVOjXtZ9hL2R3OD2SJXFtIHvsLmVvSu05kxjAgEEfbWiUrLN/18vu8wFcIEzemGdsVQw5gYcHIh9IYAgwlo2s+hkWy4Qjkgr3n9MQDgxzWdZh1pFxRJ6lvmKognpqK74cwF3s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
