travis:
  secure:
    BINSTAR_TOKEN: YWwCOXAXvmocGsEP1LRP1mIJcfUvAArXFmvVXv8DubAnIMiy2LtsMOyVpFFPpcWZW8WdXuzsRF8JLDAaG/YGX5gK1MXojwJmdabXaXDxPS+cWlNf/E1EhZ7ZnAuIRHSwM7M6QN6mf8PiZdpOEauT8fHao3snhNDL6x98aLWH36LW/x/9oKORWhKeHxcx3mXIZ+jFor233dH6jdAozX61W3HLMduPTA9npe2yGJiYJfMOuLbv+9SN5FNlEFjS/PxopYtHlYRwMdQl/pKNLxfo+QiJmcOx/Y90uMqCCoLBWuLEqB7o7sX8GiaFDO1yZQzdeFWQpUOagBw5OH7GyhPBzFDO/ZepC+Zs8Xl8AzvbfnjYaodWbb7CT0xnOBq+X/qlMTqttTedsWkYNTO9COsyoZbNvCyAKkxGL6aAozhgSCHGQwLWlD0uZSM94CQlM+8rkotH2SvHYHRONxGfhtfm4Qrk3biVxneCL+3YFpu9hlO0jd+Q9G5iKp1xakRYcJ+WagljnDrwj0VHljyV7Mrn5jRyrs+WOdJm7M60tDakN4Lv2k6OYZukEpTR07UDMA3rG8/r7fYx/s6QUJzMWpiP5O/AWL4hzc/TQKmGQrxR82cX8uEUMrHN3KovRAPyme1PQetr/2nyDo9AE540UqOf5YeOwhCwXl6zANxBMdSxX8o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
